name: DockerBuildAndPush

on:
  push:
    branches:
      - master

jobs:
  elasticsearch-head:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: build-push
        uses: docker/build-push-action@v1
        with:
          repository: xianghuzhao/elasticsearch-head
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: elasticsearch-head
          dockerfile: elasticsearch-head/Dockerfile
          tags: latest
