name: DockerBuildAndPush

on:
  push:
    branches:
      - master

jobs:
  elasticsearch-head:
    runs-on: ubuntu-18.04
    steps:
			- name: build-push
			  uses: docker/build-push-action@v1
				with:
					username: ${{ secrets.DOCKER_USERNAME }}
					password: ${{ secrets.DOCKER_PASSWORD }}
          path: elasticsearch-head
					repository: xianghuzhao/elasticsearch-head
					tags: latest
